# Generated by Django 2.2.3 on 2019-07-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuserexinfo',
            name='previous_tag',
            field=models.CharField(default=1918, max_length=200, verbose_name='previous_tag'),
            preserve_default=False,
        ),
    ]
