# Generated by Django 2.2.3 on 2019-08-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0002_xuserexinfo_previous_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmoneyobj',
            name='source_c_currency_unit',
        ),
        migrations.RemoveField(
            model_name='xmoneyobj',
            name='source_c_price',
        ),
        migrations.RemoveField(
            model_name='xmoneyobj',
            name='source_q_currency_unit',
        ),
        migrations.RemoveField(
            model_name='xmoneyobj',
            name='source_q_price',
        ),
    ]
