# Generated by Django 2.2.3 on 2019-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0003_auto_20190801_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='XTripInfo',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_trip_day', models.CharField(max_length=200, verbose_name='current trip day')),
            ],
            options={
                'verbose_name': 'trip basic info',
                'verbose_name_plural': 'trip basic info',
            },
        ),
    ]
