# Generated by Django 2.2.3 on 2019-08-03 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0004_xtripinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='XCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='currency_name')),
            ],
            options={
                'verbose_name': 'CurrencyList',
                'verbose_name_plural': 'CurrencyList',
            },
        ),
        migrations.AddField(
            model_name='xmoneyobj',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xmoneyobj',
            name='current_editor',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Current Editor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xmoneyobj',
            name='latest_updator',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Latest Updator'),
            preserve_default=False,
        ),
    ]
