# Generated by Django 2.2.3 on 2019-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0005_auto_20190803_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xcurrency',
            name='id',
        ),
        migrations.AddField(
            model_name='xcurrency',
            name='object_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
