# Generated by Django 2.2.3 on 2019-08-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0006_auto_20190804_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtripinfo',
            name='current_utc',
            field=models.CharField(default=8, max_length=200, verbose_name='current_utc'),
            preserve_default=False,
        ),
    ]
