# Generated by Django 2.2.3 on 2019-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0007_xtripinfo_current_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmoneyobj',
            name='image',
            field=models.ImageField(default=1, upload_to='mo-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xmoneyobj',
            name='previous_tag',
            field=models.CharField(default=1, max_length=200, verbose_name='previous_tag'),
            preserve_default=False,
        ),
    ]
