# Generated by Django 2.2.3 on 2019-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XMoneyRe', '0008_auto_20190805_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmoneyobj',
            name='current_editor',
        ),
    ]
